version: '3.9'
services:
  postgresdb:
    container_name: postgresdb
    image: postgres:15.2
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./src/sql/docker-database-initial.sql:/docker-entrypoint-initdb.d/docker-database-initial.sql
    restart: on-failure
    networks:
      - app-private-network

  postgresdb-pgadmin-compose:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "nettojulio@hotmail.com"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin@1234"
    ports:
      - "16543:80"
    depends_on:
      - postgresdb
    networks:
      - app-private-network

networks:
  app-private-network:
    driver: bridge
    name: app-private-network